version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  restaurant-service:
    build: .
    environment:
      POSTGRES_DSN: "host=db user=postgres password=postgres dbname=restaurant port=5432 sslmode=disable"
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data:
